### ISSUE TITLE
Host parsed data

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/HeroesDataParser#57]
Hi koliva- I started a thread at heroes-talents about the data we host that is extracted using HeroesDataParser (https://github.com/heroespatchnotes/heroes-talents/issues/79). Rather than lumping it in with the filtered & formatted JSON I think it would help the repo to maintain it separately. I expect heroespatchnotes would be glad to host that but I wanted to check with you if you'd like to host it yourself. I would be glad to maintain either way, I have a workflow in place that requires very little intervention.

The parameters I use to generate the current set of data at `heroes-talents/raw` currently:

`--output-directory "$tmpDir" --description 3 --extract-data all --extract-images all --localization all --json --warnings`

I'm open to input if you think there is a better way to do that.

**Comment by koliva8245** [comment]
Interestingly I was going to create two repos, one for the data and one for images, for my other project [Heroes.Icons](https://github.com/koliva8245/Heroes.Icons). 

However, the data files would be different.  It would be using the default description with localized text, essentially `--extract-data all --description 0 --localization --localized-text` and instead of text files for the localized text, I'll convert them to json files.

**Comment by MGatner** [comment]
Two repos is a great idea.

The description format isn't as important because I can always convert `0` to `3` on my own. I'm unclear what you would end up with from `--localization --localized-text` plus "convert them to json files", and how that differs from `--localization all --json` - could you provide an example?

**Comment by koliva8245** [comment]
Oops I mean `--localization all`.

`--localized-text` creates a **text** file with all the localized strings for each locale.  For my Heroes.Icons project I needed it to be a **json** file instead. So the localized string file being converted to a json file is just because my project.

So yeah, the localized files would be stored as a json file in the repo.

Also I forgot to mention, I probably would not be storing the xml files.

**Comment by MGatner** [comment]
Alright we're in! Let me know when you have an ETA and what I can do to help.

**Comment by koliva8245** [comment]
Done. Repos are [Heroes Data](https://github.com/HeroesToolChest/heroes-data) and [Heroes Images](https://github.com/HeroesToolChest/heroes-images).

**Comment by MGatner** [comment]
Awesome! Looking at it now. I can probably help with patch-day updates but it might take me a few to get all the formats worked out. Let me know if that's something you'd be interested in.

(Digging the new avatar.)

**Comment by koliva8245** [comment]
Sure, any help with the updates is appreciated.

**Comment by MGatner** [comment]
I've got my rig set up for contributing to heroes-data, except that I'm getting significantly different output than what it currently in the repo. The format seems to be mostly the same but values differ. I'm going to send over a PR so you can see the diff and maybe tell me what I'm doing wrong.

**Comment by MGatner** [comment]
Hosted data is live, this issue resolved. Continuing comparison conversation at https://github.com/HeroesToolChest/heroes-data/pull/1
